version: "2"

services:

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: world
      POSTGRES_PASSWORD: very_strong_password
    ports:
      - 5432:5432
    volumes:
      - ./db/seed:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data

  omnidb:
    image: taivokasper/omnidb
    ports:
      - 8080:8080
      - 25482:25482
