version: "2"

services:

  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: world
      POSTGRES_PASSWORD: very_strong_password
    ports:
      - 5432:5432
    volumes:
      - ./db/seed:/docker-entrypoint-initdb.d
